# Generated by Django 5.2.7 on 2025-10-28 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignacion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignacion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='materia',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academico.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'asignacion', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('nombre', 'grado')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('docente', 'materia', 'curso')},
        ),
    ]
