# Generated by Django 5.2.7 on 2025-10-30 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_poblar_estructura'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDidactico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='materiales_docentes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='academico.asignacion')),
            ],
        ),
    ]
