# Generated by Django 5.2.7 on 2025-10-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financiero', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='administrativo',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'ADMINISTRATIVO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_como_administrativo', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='pago',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_como_estudiante', to='usuarios.usuario'),
        ),
    ]
